# Author: Dominik Harmim <harmim6@gmail.com>

name: Documentation

on: [push, pull_request]

jobs:
  generate:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make doc
