# Author: Dominik Harmim <harmim6@gmail.com>

name: Tests

on: [push, pull_request]

jobs:
  run:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make tests
